### ISSUE TITLE
Some inconsistent model definitions in thrift and proto, is this expected?

### ISSUE THREAD

**Issue by lonewolf3739** [jaegertracing/jaeger-idl#69]
Thrift [span](https://github.com/jaegertracing/jaeger-idl/blob/master/thrift/jaeger.thrift#L52-L64) def doesn't have `process` field and [Batch](https://github.com/jaegertracing/jaeger-idl/blob/master/thrift/jaeger.thrift#L88) makes it mandatory. Proto [span](https://github.com/jaegertracing/jaeger-idl/blob/master/proto/api_v2/model.proto#L98-L136) def has `process` as mandatory span field and for [Batch](https://github.com/jaegertracing/jaeger-idl/blob/master/proto/api_v2/model.proto#L154-L159) it is nullable. Is this desired? Why should there be process field for proto span definition since it remains constant for all the telemetry within same process?

**Comment by yurishkuro** [comment]
Thrift model is used exclusively for transport, whereas Proto model is the internal domain model used by Jaeger backend, where once a batch is received each span is inflated with its own Process (memory-wise they would share the same Process object), because in the storage backends the Process is cloned into each span. So the Proto model is more flexible and allows Process to be passed either once in the Batch or individually in each Span (or even in both places with span.process taking priority).

**Comment by lonewolf3739** [comment]
Thanks, that was helpful. Good to know the reason.

**Comment by yurishkuro** [comment]
I'll add comments to the proto.
